// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	context "context"

	repository "github.com/learn/shop/repository"
	mock "github.com/stretchr/testify/mock"

	sqlx "github.com/jmoiron/sqlx"
)

// ProductRepository is an autogenerated mock type for the ProductRepository type
type ProductRepository struct {
	mock.Mock
}

// GetAllProduct provides a mock function with given fields: ctx
func (_m *ProductRepository) GetAllProduct(ctx context.Context) ([]repository.Product, error) {
	ret := _m.Called(ctx)

	var r0 []repository.Product
	if rf, ok := ret.Get(0).(func(context.Context) []repository.Product); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]repository.Product)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetProductByProductID provides a mock function with given fields: ctx, id
func (_m *ProductRepository) GetProductByProductID(ctx context.Context, id int64) (repository.Product, error) {
	ret := _m.Called(ctx, id)

	var r0 repository.Product
	if rf, ok := ret.Get(0).(func(context.Context, int64) repository.Product); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(repository.Product)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateProductQtyByProductID provides a mock function with given fields: tx, ctx, form
func (_m *ProductRepository) UpdateProductQtyByProductID(tx *sqlx.Tx, ctx context.Context, form repository.Product) error {
	ret := _m.Called(tx, ctx, form)

	var r0 error
	if rf, ok := ret.Get(0).(func(*sqlx.Tx, context.Context, repository.Product) error); ok {
		r0 = rf(tx, ctx, form)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
